[versions]
jetbrains-space-client = "68349-beta"
jetbrains-kotlinx-datetime = "0.1.1"
jetbrains-kotlinx-coroutines = "1.4.3"
ktor = "1.4.3"
junit-core = "5.7.1"
junit-platform-launcher = "1.7.1"
space-client-api = "1-SNAPSHOT"

[libraries]
jetbrains-space-client = { module = "org.jetbrains:space-sdk-jvm", version.ref = "jetbrains-space-client" }
jetbrains-kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "jetbrains-kotlinx-datetime" }
jetbrains-kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "jetbrains-kotlinx-coroutines" }
ktor-apache-http = { module = "io.ktor:ktor-client-apache", version.ref = "ktor" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform-launcher" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-core" }
junit-vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit-core" }
space-client-api = { module = "io.datalbry.jetbrains-space-client:space-client-api", version.ref = "space-client-api" }

[bundles]
junit = ["junit-platform", "junit-engine", "junit-vintage"]
