name: Release Final

on:
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        name: Setup Java
        with:
          java-version: 11

      - id: install-secret-key
        name: Install GnuPG Key
        run: |
          cat <(echo -e "${{ secrets.GNUPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Update Version
        run: >
          ./gradlew updateReleaseVersion -i

      - uses: eskatos/gradle-command-action@v1
        name: Release (Internal)
        with:
          arguments: >
            publishMavenPublicationToMavenRepository
            -Pjetbrains.space.client.id=${{ secrets.JETBRAINS_SPACE_CLIENT_ID }}
            -Pjetbrains.space.client.secret=${{ secrets.JETBRAINS_SPACE_CLIENT_SECRET }}
            -Pjetbrains.space.client.uri=${{ secrets.JETBRAINS_SPACE_CLIENT_URI }}
            -Pmaven.registry.username=${{ secrets.REGISTRY_USER }}
            -Pmaven.registry.password=${{ secrets.REGISTRY_TOKEN }}
            -Psigning.gnupg.keyName=${{ secrets.GNUPG_SECRET_NAME }}
            -Psigning.gnupg.passphrase=${{ secrets.GNUPG_SECRET_PASSWORD }}

      - uses: eskatos/gradle-command-action@v1
        name: Release (Maven Central)
        with:
          arguments: >
            publishMavenPublicationToSonatypeRepository
            -Pjetbrains.space.client.id=${{ secrets.JETBRAINS_SPACE_CLIENT_ID }}
            -Pjetbrains.space.client.secret=${{ secrets.JETBRAINS_SPACE_CLIENT_SECRET }}
            -Pjetbrains.space.client.uri=${{ secrets.JETBRAINS_SPACE_CLIENT_URI }}
            -PsonatypeUsername=${{ secrets.MAVENCENTRALUSERNAME }}
            -PsonatypePassword=${{ secrets.MAVENCENTRALPASSWORD }}
            -Psigning.gnupg.keyName=${{ secrets.GNUPG_SECRET_NAME }}
            -Psigning.gnupg.passphrase=${{ secrets.GNUPG_SECRET_PASSWORD }}

      - name: Tag
        run: >
          ./gradlew tag -i

      - name: Generate Commit Message
        run: |
          echo "##[set-output name=message;][CI] Release version $(./gradlew -q printVersion)"
        id: generate_commit_message

      - name: Push Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.generate_commit_message.outputs.message }}
          push_options: --follow-tags
